volumes:
  kestra_postgres_data:
    driver: local
  kestra_data:
    driver: local
  kestra_tmp:
    driver: local

services:
  # pgdatabase:
  #   image: postgres:18
  #   environment:
  #     POSTGRES_USER: root
  #     POSTGRES_PASSWORD: root
  #     POSTGRES_DB: ny_taxi
  #   ports:
  #     - "5432:5432"
  #   volumes:
  #     - ny_taxi_postgres_data:/var/lib/postgresql
  #   depends_on:
  #     kestra:
  #       condition: service_started

  # pgadmin:
  #   image: dpage/pgadmin4
  #   environment:
  #     - PGADMIN_DEFAULT_EMAIL=admin@admin.com
  #     - PGADMIN_DEFAULT_PASSWORD=root
  #   ports:
  #     - "8085:80"
  #   depends_on:
  #     pgdatabase:
  #       condition: service_started

  kestra_postgres:
    image: postgres:18
    volumes:
      - kestra_postgres_data:/var/lib/postgresql
    environment:
      POSTGRES_DB: kestra
      POSTGRES_USER: kestra
      POSTGRES_PASSWORD: k3str4
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -d $${POSTGRES_DB} -U $${POSTGRES_USER}"]
      interval: 30s
      timeout: 10s
      retries: 10

  kestra:
    image: kestra/kestra:latest
    pull_policy: always
    # Note that this setup with a root user is intended for development purpose.
    # Our base image runs without root, but the Docker Compose implementation needs root to access the Docker socket
    # To run Kestra in a rootless mode in production, see: https://kestra.io/docs/installation/podman-compose
    user: "root"
    command: server standalone
    volumes:
      - kestra_data:/app/storage
      - /var/run/docker.sock:/var/run/docker.sock
      - kestra_tmp:/tmp/kestra-wd
      - ./flows:/app/flows
      - ~/.config/gcloud/application_default_credentials.json:/root/.config/gcloud/application_default_credentials.json
    environment:
      GCP_PROJECT_ID: ${TF_VAR_project}                                                            
      GCP_BUCKET_NAME: ${TF_VAR_gcs_bucket_name}                                                   
      GCP_DATASET: ${TF_VAR_bq_dataset_name}                                                       
      GCP_LOCATION: ${TF_VAR_location}                                                             
      GCP_SA_IMPERSONATE: ${GCP_SA_IMPERSONATE}

      #new environment variable 
      GOOGLE_APPLICATION_CREDENTIALS: /root/.config/gcloud/application_default_credentials.json

      KESTRA_CONFIGURATION: |
        datasources:
          postgres:
            url: jdbc:postgresql://kestra_postgres:5432/kestra
            driverClassName: org.postgresql.Driver
            username: kestra
            password: k3str4
        kestra:
          variables:
            globals:
              gcp_project_id: ${TF_VAR_project}
              gcp_location: ${TF_VAR_location}
              gcp_bucket_name: ${TF_VAR_gcs_bucket_name}
              gcp_dataset: ${TF_VAR_bq_dataset_name}
              gcp_sa_impersonate: ${GCP_SA_IMPERSONATE}
          server:
            basicAuth:
              username: "admin@kestra.io" # it must be a valid email address
              password: Admin1234!
          repository:
            type: postgres
          storage:
            type: local
            local:
              basePath: "/app/storage"
          queue:
            type: postgres
          tasks:
            tmpDir:
              path: /tmp/kestra-wd/tmp
          url: http://localhost:8080/
    ports:
      - "8080:8080"
      - "8081:8081"
    depends_on:
      kestra_postgres:
        condition: service_healthy
    